version: "3"
services:
  porlet-app:
    build: .
    ports:
      - 8099:8080
    volumes:
      - '.:/app'
      - '/app/node_modules'
    # tty: true
    environment: 
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading
